### ISSUE TITLE
Problem with scan map of neighbors

### ISSUE THREAD

**Issue by mariocamaraneto** [gspd/FlexA#18]
The servers don't find others. Map is wrong.

**Comment by mariocamaraneto** [comment]
O testes estavam ocorrendo no cluster e esse era o problema.
O cluster possui NFS e tem o mapeamento de home, logo o arquivo 'flexa-server.ini' que guarda as configurações do servidor são replicado entre todas as máquinas.
Assim todas as máquinas tinham o mesmo uid, sendo assim elas não preenchiam seus mapas com tais informções, causam o erro de preenchimento.

Para "consertar" isso será criado tais informações em um diretorio local das máquinas, /tmp/, sendo comentado o código que deverá ser o de uso padrão. possibilitando assim a execução dos testes no cluster durante o desenvolvimento.

**Comment by gabrsar** [comment]
:+1:
